### PR TITLE
Paper

### PR DESCRIPTION
**Pull request by majensen**
Suggested paper edits by JOSS editor. https://github.com/openjournals/joss-reviews/issues/2643

The yeast example is not clearly described and leaves out biological details of that system that I think are relevant to the "chicken" game context. I suggest choosing a simpler example, or adding more information to clarify.

### CODE REVIEW

**Comment by AngryMaciek** [comment]
For the sake of completness I will paste additional comments from the Editor here as well:
> I would also like to see an example run in the paper that exemplifies stochastic effects. One example might be to show that if an invading population is small enough, it can disappear frequently (i.e., among many replicate simulations) even if it uses an ESS. Probably (just guessing) the fitness benefit has to exceed 1/N more or less to get a high probability of establishment. (This is also a test of the software - if a rare invader never disappears over multiple replicates, there is probably a code issue.)

**Comment by AngryMaciek** [comment]
OK, I have added one more section to the paper related to the stochastic effects (mentioned above). It presents a Hawk-Dove model where a relatively small number of invaders might fail to overtake the population. Generally, when such a simulation is driven by a payoff matrix of this particular type the invaders have no problem to take over. However, I picked such payoff values that more "randomness" is exhibited. This is visible in the growth curves and it eventually leads to the rejection of subpopulation with a fitness advantage.  

To inspect an updated version it might be easiest to use (on branch `paper`): https://whedon.theoj.org/  
To code underlying these simulations is in the "Appendix 1" section of the [use case test notebook](https://github.com/AngryMaciek/angry-moran-simulator/blob/paper/tests/usecase.ipynb)

In case you would like to suggest modifications to the new section I guess you should update your fork with `paper` branch first and then commit to this PR.

**Comment by AngryMaciek** [comment]
Dear @majensen,
We have re-written section (B) in the text and clarified the description a little; yeasts are a good example from the literature so we would like to keep it. Please let me know if you would like to introduce more changes and if not I will merge.

**Comment by majensen** [comment]
I like the new description and agree its a fascinating example system. Please go ahead and merge up.

**Pull request merged**
